'use strict'

export const START_UPDATE_EMPLOYEE = 'Warehouse/START_UPDATE_EMPLOYEE'
export const CANCEL_UPDATE_EMPLOYEE = 'Warehouse/CANCEL_UPDATE_EMPLOYEE'

export const EMPLOYEE_CREATED = 'Employee/EMPLOYEE_CREATED'
export const EMPLOYEE_UPDATED = 'Employee/EMPLOYEE_UPDATED'
export const EMPLOYEE_DELETED = 'Employee/EMPLOYEE_DELETED'

export const LOADING_EMPLOYEES = 'Employee/LOADING_EMPLOYEES'
export const SET_EMPLOYEE_LIST = 'Employee/SET_EMPLOYEE_LIST'
